Speed up support
commons-stack/swissmem-dapp pull request #312
Opened 2021-06-08 00:23 UTC by aminlatifi

Poll smart contract events to see whether the transaction went through or not.
#289

2021-06-14 17:18 UTC, MerlinEgalite requested changes
Just a Typo but everything seems good to me!

2021-06-14 17:18 UTC, MerlinEgalite commented on src/blockchain/allowanceHelper.js
> +    ERC20Cotract.approve(config.givethBridgeAddress, amount)
```suggestion
    ERC20Contract.approve(config.givethBridgeAddress, amount)
```

2021-06-14 17:18 UTC, MerlinEgalite commented on src/blockchain/allowanceHelper.js
>  const createAllowance = async (ERC20Cotract, account, amount) => {
```suggestion
const createAllowance = async (ERC20Contract, account, amount) => {
```

2021-06-14 17:18 UTC, MerlinEgalite commented on src/blockchain/allowanceHelper.js
> +        const web3 = ERC20Cotract.getWeb3();
```suggestion
        const web3 = ERC20Contract.getWeb3();
```

2021-06-14 17:18 UTC, MerlinEgalite commented on src/blockchain/allowanceHelper.js
> +              const events = await ERC20Cotract.peApproval({
```suggestion
              const events = await ERC20Contract.peApproval({
```

2021-06-15 08:42 UTC, aminlatifi commented
> Just a Typo but everything seems good to me!

Thanks @MerlinEgalite

2021-06-15 08:44 UTC, merged