CSLove page
commons-stack/swissmem-dapp pull request #314
Opened 2021-06-14 12:37 UTC by kristoferlund

Closes #313

2021-06-14 17:32 UTC, kristoferlund commented
Don't merge, realised I forgot something.

2021-06-14 17:39 UTC, MerlinEgalite requested changes
Just a small change to be up to date with Metamask recommendations

2021-06-14 17:39 UTC, MerlinEgalite commented on src/components/OnboardProvider.js
> +    await provider.request({
`provider.request()` can be used for `addCSTK` too as `sendAsync` is deprecated now: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-sendasync-deprecated

2021-06-15 12:53 UTC, MerlinEgalite approved these changes
LGTM!

2021-06-15 12:53 UTC, merged